eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://peer1:7001/eureka/
  server:
    enable-self-preservation: false
server:
  port: 7002
